#ifndef LX16A_DEFINES_H
#define LX16A_DEFINES_H

//baud rate for Serial object
#define LX16A_BAUDRATE 115200

// header frame
#define LX16A_FRAME_HEADER 0x55

// broadcast ID to command all servos
#define LX16A_BROADCAST_ID 0xFE
#define LX16A_DEFAULT_ID 0x01

// COMMAND IDs
#define LX16A_COMMID_MOVE_TIME_WRITE 1
#define LX16A_COMMID_SERVO_ID_WRITE 13
#define LX16A_COMMID_MODE_WRITE 29
#define LX16A_COMMID_TRIGGERED_MOVE_TIME_WRITE 7
#define LX16A_COMMID_MOVE_TIME_TRIGGER_WRITE 11

// DATA LENGTHS
#define LX16A_DATLEN_MOVE_TIME_WRITE 7
#define LX16A_DATLEN_SERVO_ID_WRITE 4
#define LX16A_DATLEN_MODE_WRITE 7
#define LX16A_DATLEN_TRIGGERED_MOVE_TIME_WRITE 7
#define LX16A_DATLEN_MOVE_TIME_TRIGGER_WRITE 3

// MISC
#define LX16A_POSITION_MODE 0x00
#define LX16A_VELOCITY_MODE 0x01

#define LX16A_DEFAULT_MODE 0x00
#define LX16A_NULL 0x00
#endif